Authorization cloud mail
kalash9747/kalash-autotests pull request #1
Opened 2022-05-15 14:04 UTC by kalash9747

Добавил модули util и cloudmail.
Хранение пользовательских данных в зашифрованном виде в отдельном файле.
Добавил класс для упрощения отправки Api запросов клиентом java 11 .
Тесты:
      -api авторизация в облаке Mail.ru.
      -проверка присутствия имен файлов корневого каталога в теле ответа .

![image](https://user-images.githubusercontent.com/82981820/168476813-2ec28cac-26db-4ecd-8682-7d2ec416f514.png)

2022-05-16 21:54 UTC, dKusakin requested changes

2022-05-16 21:54 UTC, dKusakin commented on build.gradle
> +        sourceCompatibility = JavaVersion.VERSION_11
Не очень корректно внутри `tasks` указывать версию. Эти параметры чуть глобальнее, указывай хотя бы просто внутри `subprojects`

2022-05-16 21:54 UTC, dKusakin commented on cloudmail/build.gradle
> +    version = '2.15.0'
В куче мест одни те же версии одних и тех же, по сути, ядер артефактов.
А когда обновлять решишься про все вспомнишь?
Хотя бы в корневом `build.gradle` в секции `ext` заведи под них переменные

2022-05-16 21:54 UTC, dKusakin commented on cloudmail/src/main/java/api/CloudMailApi.java
> +        return step("Авторизоваться под пользователем " + user.getLogin(), () -> {
А почему степ не аннотацией, а внутри метода?

2022-05-16 21:54 UTC, dKusakin commented on cloudmail/src/main/java/api/CloudMailApi.java
> +            String authBody = String.format("username=%s&Login=%s&password=%s&Password=%s&saveauth=1&act_token=%s&page=%s",
Хм, как-то не очень выглядит. Мб замутить свой `BodyPublisher` для `form-param`?
Это, конечно, скорее будет а-ля адаптер к `StringPublisher`, но всё равно.
Мне просто не очень нравится, что ты в тело просто `String` пихаешь. Логичнее туда как раз объект поинтереснее класть. Но это больше на подумать, по факту для начала и так хорошо)

2022-05-16 21:54 UTC, dKusakin commented on cloudmail/src/main/java/api/CloudMailApi.java
> +        return act.isPresent() ? act.get().getValue() : "";
После `findFirst()`:
```
    .map(HttpCookie::getValue)
    .orElse("");
```

2022-05-16 21:54 UTC, dKusakin commented on cloudmail/src/main/java/api/CloudMailApi.java
> +        return base.get(URI.create(baseUri + "/api/v2/feed"),
Кстати, `feed` не совсем по заданию. Он получает то ли вообще все, то ли недавние, но суть в том, что из подпапок тоже достает

2022-05-16 21:54 UTC, dKusakin commented on cloudmail/src/test/java/api/HomeDirectoryTest.java
> +        var actualFileNames = cloudMailApi.feed()
`var`  - тоже холиварная тема)
Главное - не злоупотреблять

2022-05-16 21:54 UTC, dKusakin commented on cloudmail/src/test/java/api/HomeDirectoryTest.java
> +public class HomeDirectoryTest {
Хоть я этого и не указал, но, если не сложно, мб будем разлогиниваться?

2022-05-16 21:54 UTC, dKusakin commented on util/build.gradle
> +    implementation 'com.fasterxml.jackson.core:jackson-databind:2.13.2'
Оставлю про версии тут тоже, чтобы не забыть посмотреть

2022-05-16 21:54 UTC, dKusakin commented on util/src/main/java/encryption/UserRole.java
> + * Интерфейс рпользовательских ролей
**р**пользовательских

2022-05-17 15:55 UTC, kalash9747 commented on build.gradle
> +        sourceCompatibility = JavaVersion.VERSION_11
сделал

2022-05-17 15:55 UTC, kalash9747 commented on cloudmail/build.gradle
> +    version = '2.15.0'
сделал

2022-05-17 15:55 UTC, kalash9747 commented on cloudmail/src/main/java/api/CloudMailApi.java
> +        return step("Авторизоваться под пользователем " + user.getLogin(), () -> {
сделал

2022-05-17 15:55 UTC, kalash9747 commented on cloudmail/src/main/java/api/CloudMailApi.java
> +            String authBody = String.format("username=%s&Login=%s&password=%s&Password=%s&saveauth=1&act_token=%s&page=%s",
сделал

2022-05-17 15:56 UTC, kalash9747 commented on cloudmail/src/main/java/api/CloudMailApi.java
> +        return act.isPresent() ? act.get().getValue() : "";
крутяк) сделал

2022-05-17 15:56 UTC, kalash9747 commented on cloudmail/src/main/java/api/CloudMailApi.java
> +        return base.get(URI.create(baseUri + "/api/v2/feed"),
сделал

2022-05-17 15:56 UTC, kalash9747 commented on cloudmail/src/test/java/api/HomeDirectoryTest.java
> +        var actualFileNames = cloudMailApi.feed()
а он вообще затесался случайно, сделал

2022-05-17 15:57 UTC, kalash9747 commented on cloudmail/src/test/java/api/HomeDirectoryTest.java
> +public class HomeDirectoryTest {
сделал, проверил - работает , на попытку снова кинуть запрос прилетает ответ неавторизован

2022-05-17 15:58 UTC, kalash9747 commented on util/build.gradle
> +    implementation 'com.fasterxml.jackson.core:jackson-databind:2.13.2'
сделал

2022-05-17 15:58 UTC, kalash9747 commented on util/src/main/java/encryption/UserRole.java
> + * Интерфейс рпользовательских ролей
сделал

2022-05-17 19:32 UTC, dKusakin commented on cloudmail/src/main/java/api/CloudMailApi.java
> +                new QueryParam("username", user.getLogin()),
А я думал мапой замутить. Тут бы через `Map.of()` (11-я, же джава, можем себе позволить) попроще смотрелось бы

2022-05-17 19:44 UTC, dKusakin commented on util/src/main/java/api/QueryParam.java
> +public class QueryParam {
В принципе, в качестве этой штуки мог бы выступать и `AbstractMap.SimpleEntry`

2022-05-17 19:45 UTC, dKusakin approved these changes

2022-05-19 23:30 UTC, merged