Auth cloud mail UI
kalash9747/kalash-autotests pull request #3
Opened 2022-05-23 12:07 UTC by kalash9747

Сделал Ui тесты облака с использованием БД 
![image](https://user-images.githubusercontent.com/82981820/169815669-16dd49dc-c30b-4979-a37f-35ad78b2ae45.png)
![image](https://user-images.githubusercontent.com/82981820/169815752-d2e38880-8fed-4746-9ac2-102760edfb2c.png)
![image](https://user-images.githubusercontent.com/82981820/169815871-9bdf90f2-783e-45dc-a1ec-3e949786dd41.png)

2022-05-23 20:09 UTC, dKusakin requested changes
Комменты написал + бд мне никто не дал, чтобы потыкать :)

2022-05-23 20:09 UTC, dKusakin commented on cloudmail/build.gradle
> +    testRuntimeOnly browserUpProxyCore
`selenide-proxy` не устроил? Да и нужен ли он, если ты `FOLDER` заюзал?

2022-05-23 20:09 UTC, dKusakin commented on cloudmail/src/main/java/models/dbModels/CloudFileInfo.java
> + * Представление фойла в базе данных
ф**а**йла

2022-05-23 20:09 UTC, dKusakin commented on cloudmail/src/main/java/models/dbModels/CloudFileInfo.java
> +        return name + contentextension;
Ты расширения в БД сразу с точкой хранишь?

2022-05-23 20:09 UTC, dKusakin commented on cloudmail/src/main/java/models/dbModels/CloudFileInfo.java
> +        try (FileOutputStream fos = new FileOutputStream(file.getPath())) {
Просто `file` в конструктор чем не катит?

2022-05-23 20:09 UTC, dKusakin commented on util/src/main/java/annotations/Column.java
> +public @interface Column {
Что-то нигде не нашел использование, нужна?

2022-05-23 20:09 UTC, dKusakin commented on cloudmail/src/main/java/pages/AuthorizationFrame.java
> +        nextButton().shouldBe(Condition.visible).click();
Ты знаешь, что делать)

2022-05-23 20:09 UTC, dKusakin commented on cloudmail/src/main/java/pages/HomePage.java
> +        cell.$(byText(extension.replace(".", ""))).shouldBe(visible);
Похоже, и правда с точкой. А зачем? Можно ж было б без неё в БД хранить, т.к. смысл в этой точке?

2022-05-23 20:09 UTC, dKusakin commented on cloudmail/src/main/java/pages/HomePage.java
> +                .filterBy(matchText(name))
Тебе именно регулярка нужна?
Простой `text` будет тоже по частичному соответствию искать (там `contains` под капотом)

2022-05-23 20:09 UTC, dKusakin commented on cloudmail/src/main/java/pages/HomePage.java
> +        downloadButton().click();
А зачем этот клик? Разве `download` ниже за тебя не кликнет?

2022-05-23 20:09 UTC, dKusakin commented on cloudmail/src/main/java/pages/HomePage.java
> +            e.printStackTrace();
А есть смысл продолжать? Кидал бы тут `AssertionFailedError` и всего делов

2022-05-23 20:09 UTC, dKusakin commented on cloudmail/src/test/java/ui/HomePageTest.java
> +        fileFromDB = getAllCloudFilesFromDB().get(0).setName(currentTimeMillis() + "");
Ээ, а чего `get(0)` ? Всё время будет первую брать? Не, надо случайно тыкать

2022-05-23 20:09 UTC, dKusakin commented on cloudmail/src/test/java/ui/HomePageTest.java
> +    private static CloudFileInfo fileFromDB;
Есть тут смысл от статика?

2022-05-23 20:09 UTC, dKusakin commented on cloudmail/src/test/java/ui/HomePageTest.java
> +                .uploadFile(fileFromDB.toTempFile())
Я изначально задумывал эти кейсы как один выгружает, а второй загружает. Теперь понимаю, что нужен ещё третий, который удаляет)
Есть мысль, как это реализовать с помощью БД и `assume`. Например, при выгрузке получать доступные файлы из БД, понять, каких нет на UI, и из оставшихся выбрать какой-нибудь для выгрузки. В `assume` поверять, что ещё есть что выгружать. С остальными аналогично. По идее, так это будет более атомарно, но надо поприседать. Да и не уверен, что оно надо

2022-05-23 20:09 UTC, dKusakin commented on cloudmail/src/test/java/ui/HomePageTest.java
> +            return readFileToByteArray(file);
Это же 11-я джава! Тут у `InputStream` (а, значит, и у `FileInputStream`) есть прекрасный метод `readAllBytes()`

2022-05-23 20:09 UTC, dKusakin commented on cloudmail/src/test/java/ui/HomePageTest.java
> +public class HomePageTest extends TestRunner {
Лан, в QE пропущу тут наследование, в SQE, скорее всего, уже нет)

2022-05-23 20:21 UTC, kalash9747 commented on cloudmail/src/test/java/ui/HomePageTest.java
> +public class HomePageTest extends TestRunner {
в SQE так и не буду делать)

2022-05-23 22:29 UTC, kalash9747 commented on cloudmail/build.gradle
> +    testRuntimeOnly browserUpProxyCore
убрал

2022-05-23 22:30 UTC, kalash9747 commented on cloudmail/src/main/java/models/dbModels/CloudFileInfo.java
> + * Представление фойла в базе данных
поправил

2022-05-23 22:30 UTC, kalash9747 commented on cloudmail/src/main/java/models/dbModels/CloudFileInfo.java
> +        return name + contentextension;
убрал точку  и из БД и в проекте

2022-05-23 22:30 UTC, kalash9747 commented on cloudmail/src/main/java/models/dbModels/CloudFileInfo.java
> +        try (FileOutputStream fos = new FileOutputStream(file.getPath())) {
сделал

2022-05-23 22:31 UTC, kalash9747 commented on util/src/main/java/annotations/Column.java
> +public @interface Column {
затесалась после экспериментов, убрал

2022-05-23 22:31 UTC, kalash9747 commented on cloudmail/src/test/java/ui/HomePageTest.java
> +        fileFromDB = getAllCloudFilesFromDB().get(0).setName(currentTimeMillis() + "");
верно, сделал

2022-05-23 22:32 UTC, kalash9747 commented on cloudmail/src/test/java/ui/HomePageTest.java
> +    private static CloudFileInfo fileFromDB;
убрал, мои грабли ходят по пятам

2022-05-23 22:32 UTC, kalash9747 commented on cloudmail/src/test/java/ui/HomePageTest.java
> +            return readFileToByteArray(file);
сделал

2022-05-23 22:33 UTC, kalash9747 commented on cloudmail/src/test/java/ui/HomePageTest.java
> +                .uploadFile(fileFromDB.toTempFile())
Вопрос открытый

2022-05-23 22:34 UTC, kalash9747 commented
все поправил, кроме тестов для remove, пока вопрос на обсуждении

2022-05-25 21:37 UTC, dKusakin commented on cloudmail/src/main/java/pages/HomePage.java
> +            throw new AssertionFailedError("Не удалось скачать файл");
Всё же вторым аргументом `e` неплохо бы подвязать. Так `StackTrace` туда передастся оригинальный тоже. Ну и вывод выше тебе будет ни к чему

2022-05-25 22:22 UTC, dKusakin requested changes
Закрытие файла и обратная итерация по коллекции

2022-05-25 22:22 UTC, dKusakin commented on cloudmail/src/test/java/ui/HomePageTest.java
> +            return new FileInputStream(file).readAllBytes();
А закрывать кто будет? Думаю, ты знаешь, какой конструкцией

2022-05-25 22:22 UTC, dKusakin commented on cloudmail/src/test/java/ui/HomePageTest.java
> +        File fileFromCloud = homePage.downloadRandomFile();
Мы же с тобой говорили, что качаем не случайный файл, а какой-нибудь, соответствующий какому-нибудь файлу из БД по имени. Ты что-то другое тут решил?

2022-05-25 22:22 UTC, dKusakin commented on cloudmail/src/test/java/ui/HomePageTest.java
> +        for (int i = 0; i < cells.size() - 1; i++) {
А если цикл с конца сделать, то мб попроще выйдет?

2022-05-25 22:22 UTC, dKusakin commented on cloudmail/src/test/java/ui/HomePageTest.java
> +        for (int i = 0; i < cells.size() - 1; i++) {
Вообще не рекомендуют итерировать `ElementsCollection`, так что надо это делать осторожно
Я б, наверное, вытащил эти имена фильтром и потом уже по именам бы удалял. Это так, мысли вслух)

2022-05-26 20:10 UTC, dKusakin commented on cloudmail/src/main/java/pages/HomePage.java
> +        cells().asFixedIterable().forEach(cell -> names.add(getNameWithExtFromCell(cell)));
В новой версии селенида этим `Iterable` добавили `stream`)
Можно поглядеть на досуге

2022-05-27 08:24 UTC, dKusakin requested changes

2022-05-27 08:24 UTC, dKusakin commented on cloudmail/src/test/java/ui/HomePageTest.java
> +                cells = homePage.cells();
А это зачем? У тебя же коллекция самообновляемая

2022-05-27 08:24 UTC, dKusakin commented on cloudmail/src/test/java/ui/HomePageTest.java
> +    private CloudFileInfo fileFromDB;
Этот парень очень тут нужен?

2022-05-27 08:24 UTC, dKusakin commented on cloudmail/src/test/java/ui/HomePageTest.java
> +                .orElse(new CloudFileInfo());
По-моему, тут логичнее не пустой объект давать, а кидать через `orElseThrow` какой-нибудь `IllegalStateException`, ведь такого, по идее, в штатной ситуации не может быть (имя же изначально сверяли)

2022-05-27 08:24 UTC, dKusakin commented on cloudmail/src/test/java/ui/HomePageTest.java
> +                assertArrayEquals(fileFromDB.getContentbytes(), fileToByteArray(fileFromCloud),
Вот, кстати, из-за предыдущего пустого объекта эта проверка при скачанном пустом файле может быть ложноположительной

2022-05-31 06:47 UTC, dKusakin approved these changes

2022-05-31 07:50 UTC, merged