Perf api check
kalash9747/kalash-autotests pull request #4
Opened 2022-06-02 21:25 UTC by kalash9747

Добавил новый модуль perf, подключил jooq, сделал тесты  добавления пользователя и покупки автомобиля пользователем без дома

![image](https://user-images.githubusercontent.com/82981820/171740962-32cbbe04-1625-48c3-bed6-1b74bf3fd988.png)
![image](https://user-images.githubusercontent.com/82981820/171741006-7cc4c370-e03e-4412-9955-92fa6e957750.png)

2022-06-03 19:40 UTC, dKusakin commented on perf/build.gradle
> +    autoconfigure = true
Плагин аллюра решил старый использовать?

2022-06-03 19:41 UTC, dKusakin commented on perf/build.gradle
> +    testImplementation allureCommandLine
Зачем тебе commandline внутри проекта?

2022-06-03 20:24 UTC, dKusakin requested changes

2022-06-03 20:24 UTC, dKusakin commented on perf/build.gradle
> +                    url = 'jdbc:postgresql://77.50.236.203:4832/pflb_trainingcenter'
Хм, затягивать бы это из конфигов..
Не выйдет как-то из ресурсов подтянуть?

2022-06-03 20:24 UTC, dKusakin commented on perf/src/main/java/encryption/PerfUserRole.java
> +    perfDBReader,
Вообще это константы, а константы принято в другом стиле записывать

2022-06-03 20:24 UTC, dKusakin commented on perf/src/main/java/database/PerfDbExecutor.java
> +                .and(PERSON.SEX.eq(true))
А чего это ты тут дам обделил?)

2022-06-03 20:24 UTC, dKusakin commented on perf/src/test/java/usersTests/PerfApiTest.java
> +    @DisplayName("Проверка добаления пользователя")
доба**в**ления

2022-06-03 20:24 UTC, dKusakin commented on perf/src/test/java/usersTests/PerfApiTest.java
> +        PersonRecord person = new PersonRecord(null, 25, "Tony", valueOf(247000), "Stark", true, null);
"Тест не должен зависеть от конкретных тестовых данных"
Посмотри в сторону [`Faker`'а](https://github.com/DiUS/java-faker) или чего-то подобного

2022-06-03 20:24 UTC, dKusakin commented on perf/src/test/java/usersTests/PerfApiTest.java
> +                assertEquals(countRecordsBefore + 1, dbExecutor.getCountPersonRecords(person),
Хотелось бы не только количество, но и ответ проверить, там ведь прилетает созданный пользак с id.
Мб сначала максимальный id проверять, а потом проверять, что у вернувшегося он не меньше? Ну и потом соответствие данных ещё

2022-06-03 20:24 UTC, dKusakin commented on perf/src/test/java/usersTests/PerfApiTest.java
> +        return dbExecutor.getCarRecords().stream()
А я правильно понял, что сначала нашли все автомобили запросом, а потом фильтранули результат уже в джаве? Мб стоило сразу в БД нужный запрос кидать?

2022-06-03 20:24 UTC, dKusakin commented on perf/src/test/java/usersTests/PerfApiTest.java
> +        return dbExecutor.getPersonRecords().stream()
Тут вопрос аналогичный автомобилям

2022-06-03 20:24 UTC, dKusakin commented on perf/src/test/java/usersTests/PerfApiTest.java
> +        assumeTrue(person.getMoney().compareTo(car.getPrice()) >= 0,
Выход интересный, просто взять самого богатого человека и самый дешёвый автомобиль)
Я бы исхитрялся через запрос, т.е. декартово произведение человеков и автомобилей, а потом их фильтрация по "автомобиль не должен принадлежать человеку и кол-во денег человека >= стоимость автомобиля" и выбор любой полученной записи

2022-06-03 20:24 UTC, dKusakin commented on perf/src/test/java/usersTests/PerfApiTest.java
> +                "В базе данных нет пользователя без дома, у которого хватает денег, хотя бы на самую дешевую машину");
Между "денег" и "хотя бы" запятая не нужна

2022-06-03 20:24 UTC, dKusakin commented on util/src/main/java/api/BaseHttpMethods.java
> +    public HttpResponseFacade post(URI uri) {
Что-то сразу не подумал, но если в 70 и 78 строке написать не просто `headers == null`, а расширить до `headers == null || headers.length < 1`, то мб от части методов удастся избавиться, ведь `vararg` поддерживает и отсутствие аргументов

2022-06-04 10:34 UTC, kalash9747 commented on perf/src/test/java/usersTests/PerfApiTest.java
> +        return dbExecutor.getCarRecords().stream()
Да правильно, здесь я просто хотел некоторые кейсы стримами , а некоторые запросом в БД, так как третий кейс подразумевает более сложный запрос , его решил запросом в БД ,а эти стримами,  если это принципиально могу переделать если нет, то оставил бы)

2022-06-04 10:38 UTC, kalash9747 commented on perf/build.gradle
> +    autoconfigure = true
да, пока хотел на старых а переезд на новые версии аллюра и селенида  хотел сделать по завершении всего задания

2022-06-04 16:43 UTC, kalash9747 commented on perf/src/test/java/usersTests/PerfApiTest.java
> +        return dbExecutor.getPersonRecords().stream()
оставил самого богатого пользователя к самому дешевому авто

2022-06-04 16:43 UTC, kalash9747 commented on perf/src/test/java/usersTests/PerfApiTest.java
> +        assumeTrue(person.getMoney().compareTo(car.getPrice()) >= 0,
оставил самого богатого пользователя к самому дешевому авто

2022-06-04 17:42 UTC, dKusakin commented on perf/src/main/java/models/PersonInfo.java
> +        return money.doubleValue();
Сразу не обратил внимание. Зачем перегонять в `double`?

2022-06-04 17:42 UTC, dKusakin commented on perf/src/main/java/models/PersonInfo.java
> +    public PersonInfo setMoney(double money) {
Аналогично, почему сразу не из `BigDecimal`?

2022-06-04 17:53 UTC, dKusakin requested changes

2022-06-04 17:53 UTC, dKusakin commented on perf/src/test/java/usersTests/PerfApiTest.java
> +        PersonInfo personRq = new PersonInfo(new PersonRecord(null, faker.number().numberBetween(18, 100),
Мб лучше через цепочку сеттеров? А то эта штука как-то тяжко читается с кучей параметров

2022-06-05 19:47 UTC, dKusakin approved these changes

2022-06-07 00:01 UTC, merged