added queries DB
kalash9747/kalash-autotests pull request #5
Opened 2022-06-07 00:08 UTC by kalash9747

Добавил тест покупки не электрического автомобиля , и тест который выявляет баг : суммарное количество автомобилей в доме не должно превышать общее количество мест в этом доме
![image](https://user-images.githubusercontent.com/82981820/172268890-cec9ec7c-3a4a-4332-993c-5eeaa7bc4e36.png)
![image](https://user-images.githubusercontent.com/82981820/172269050-737e7793-fc64-4eaf-be67-6ce18499be2d.png)

2022-06-07 18:48 UTC, dKusakin commented on perf/src/test/java/usersTests/PerfApiTest.java
> +        System.out.println(dbExecutor.getUsersInHousesWithFreePlaces());
Отладка?

2022-06-07 19:06 UTC, dKusakin requested changes
- отладочная информация не особо нужна
- мелкие ремарки в ассертах

Плюс теперь жду баг репорта

2022-06-07 19:06 UTC, dKusakin commented on perf/src/test/java/usersTests/PerfApiTest.java
> +                        "Количество денег должно было уменьшиться на цену автомобиля"));
Тут только при ошибке вывод будет не очень. Там будет "Ожидалось: 0 Актуальное: какое-то непонятное число"
Лучше в сообщение добавить, что там за реальные числа

2022-06-07 19:06 UTC, dKusakin commented on perf/src/test/java/usersTests/PerfApiTest.java
> +        perfApi.buyCar(person.getId(), car.getId());
По идее, уже вот тут должны были схватить ошибку.
Мб через `assertAll` бахнуть проверки кода ответа и вот ту ниже?

2022-06-09 19:31 UTC, dKusakin commented on perf/src/test/java/usersTests/PerfApiTest.java
> +                            "Expected: " + actualMoney + "\nActual: " + actualMoney);
`actualMoney` даже в `Expected:`

2022-06-09 21:21 UTC, dKusakin commented on perf/src/test/java/usersTests/PerfApiTest.java
> +        List<PersonRecord> personRecords = dbExecutor.getUsersWhereCountCarsLessSumPlaces();
Что-то я данные обеспечил (дом с 2 местами и 2 пользаками, имеющими по одной машине), но запрос их не находит

2022-06-09 21:22 UTC, dKusakin commented on perf/src/test/java/usersTests/PerfApiTest.java
> +                "Не удалось найти пользователей живущих в доме без свободных парковочных мест");
"пользователей**,** живущих"

2022-06-10 06:36 UTC, kalash9747 commented on perf/src/test/java/usersTests/PerfApiTest.java
> +        List<PersonRecord> personRecords = dbExecutor.getUsersWhereCountCarsLessSumPlaces();
поправил

2022-06-10 06:36 UTC, kalash9747 commented on perf/src/test/java/usersTests/PerfApiTest.java
> +                            "Expected: " + actualMoney + "\nActual: " + actualMoney);
поправил

2022-06-10 06:36 UTC, kalash9747 commented on perf/src/test/java/usersTests/PerfApiTest.java
> +                "Не удалось найти пользователей живущих в доме без свободных парковочных мест");
поправил

2022-06-10 06:44 UTC, dKusakin approved these changes

2022-06-10 06:44 UTC, merged